export type Country = {
	label: string
	dial_code: string
	value: string
}

export const countries: Country[] = [
	{ label: 'Афганистан', dial_code: '+93', value: 'AF' },
	{ label: 'Аландские острова', dial_code: '+358', value: 'AX' },
	{ label: 'Албания', dial_code: '+355', value: 'AL' },
	{ label: 'Алжир', dial_code: '+213', value: 'DZ' },
	{ label: 'Американское Самоа', dial_code: '+1684', value: 'AS' },
	{ label: 'Андорра', dial_code: '+376', value: 'AD' },
	{ label: 'Ангола', dial_code: '+244', value: 'AO' },
	{ label: 'Ангилья', dial_code: '+1264', value: 'AI' },
	{ label: 'Антарктида', dial_code: '+672', value: 'AQ' },
	{ label: 'Антигуа и Барбуда', dial_code: '+1268', value: 'AG' },
	{ label: 'Аргентина', dial_code: '+54', value: 'AR' },
	{ label: 'Армения', dial_code: '+374', value: 'AM' },
	{ label: 'Аруба', dial_code: '+297', value: 'AW' },
	{ label: 'Австралия', dial_code: '+61', value: 'AU' },
	{ label: 'Австрия', dial_code: '+43', value: 'AT' },
	{ label: 'Азербайджан', dial_code: '+994', value: 'AZ' },
	{ label: 'Багамы', dial_code: '+1242', value: 'BS' },
	{ label: 'Бахрейн', dial_code: '+973', value: 'BH' },
	{ label: 'Бангладеш', dial_code: '+880', value: 'BD' },
	{ label: 'Барбадос', dial_code: '+1246', value: 'BB' },
	{ label: 'Беларусь', dial_code: '+375', value: 'BY' },
	{ label: 'Бельгия', dial_code: '+32', value: 'BE' },
	{ label: 'Белиз', dial_code: '+501', value: 'BZ' },
	{ label: 'Бенин', dial_code: '+229', value: 'BJ' },
	{ label: 'Бермуды', dial_code: '+1441', value: 'BM' },
	{ label: 'Бутан', dial_code: '+975', value: 'BT' },
	{ label: 'Боливия', dial_code: '+591', value: 'BO' },
	{ label: 'Босния и Герцеговина', dial_code: '+387', value: 'BA' },
	{ label: 'Ботсвана', dial_code: '+267', value: 'BW' },
	{ label: 'Бразилия', dial_code: '+55', value: 'BR' },
	{ label: 'Бруней-Даруссалам', dial_code: '+673', value: 'BN' },
	{ label: 'Болгария', dial_code: '+359', value: 'BG' },
	{ label: 'Буркина-Фасо', dial_code: '+226', value: 'BF' },
	{ label: 'Бурунди', dial_code: '+257', value: 'BI' },
	{ label: 'Камбоджа', dial_code: '+855', value: 'KH' },
	{ label: 'Камерун', dial_code: '+237', value: 'CM' },
	{ label: 'Канада', dial_code: '+1', value: 'CA' },
	{ label: 'Кабо-Верде', dial_code: '+238', value: 'CV' },
	{ label: 'Чад', dial_code: '+235', value: 'TD' },
	{ label: 'Чили', dial_code: '+56', value: 'CL' },
	{ label: 'Китай', dial_code: '+86', value: 'CN' },
	{ label: 'Колумбия', dial_code: '+57', value: 'CO' },
	{ label: 'Коморы', dial_code: '+269', value: 'KM' },
	{ label: 'Конго', dial_code: '+242', value: 'CG' },
	{ label: 'Демократическая Республика Конго', dial_code: '+243', value: 'CD' },
	{ label: 'Коста-Рика', dial_code: '+506', value: 'CR' },
	{ label: 'Кот-д’Ивуар', dial_code: '+225', value: 'CI' },
	{ label: 'Хорватия', dial_code: '+385', value: 'HR' },
	{ label: 'Куба', dial_code: '+53', value: 'CU' },
	{ label: 'Кипр', dial_code: '+357', value: 'CY' },
	{ label: 'Чехия', dial_code: '+420', value: 'CZ' },
	{ label: 'Дания', dial_code: '+45', value: 'DK' },
	{ label: 'Египет', dial_code: '+20', value: 'EG' },
	{ label: 'Эстония', dial_code: '+372', value: 'EE' },
	{ label: 'Эфиопия', dial_code: '+251', value: 'ET' },
	{ label: 'Финляндия', dial_code: '+358', value: 'FI' },
	{ label: 'Франция', dial_code: '+33', value: 'FR' },
	{ label: 'Грузия', dial_code: '+995', value: 'GE' },
	{ label: 'Германия', dial_code: '+49', value: 'DE' },
	{ label: 'Индия', dial_code: '+91', value: 'IN' },
	{ label: 'Индонезия', dial_code: '+62', value: 'ID' },
	{ label: 'Иран', dial_code: '+98', value: 'IR' },
	{ label: 'Ирак', dial_code: '+964', value: 'IQ' },
	{ label: 'Ирландия', dial_code: '+353', value: 'IE' },
	{ label: 'Израиль', dial_code: '+972', value: 'IL' },
	{ label: 'Италия', dial_code: '+39', value: 'IT' },
	{ label: 'Япония', dial_code: '+81', value: 'JP' },
	{ label: 'Казахстан', dial_code: '+77', value: 'KZ' },
	{ label: 'Кения', dial_code: '+254', value: 'KE' },
	{ label: 'Киргизия', dial_code: '+996', value: 'KG' },
	{ label: 'Латвия', dial_code: '+371', value: 'LV' },
	{ label: 'Ливан', dial_code: '+961', value: 'LB' },
	{ label: 'Литва', dial_code: '+370', value: 'LT' },
	{ label: 'Люксембург', dial_code: '+352', value: 'LU' },
	{ label: 'Малайзия', dial_code: '+60', value: 'MY' },
	{ label: 'Мальдивы', dial_code: '+960', value: 'MV' },
	{ label: 'Мальта', dial_code: '+356', value: 'MT' },
	{ label: 'Мексика', dial_code: '+52', value: 'MX' },
	{ label: 'Молдова', dial_code: '+373', value: 'MD' },
	{ label: 'Монголия', dial_code: '+976', value: 'MN' },
	{ label: 'Черногория', dial_code: '+382', value: 'ME' },
	{ label: 'Марокко', dial_code: '+212', value: 'MA' },
	{ label: 'Нидерланды', dial_code: '+31', value: 'NL' },
	{ label: 'Новая Зеландия', dial_code: '+64', value: 'NZ' },
	{ label: 'Нигерия', dial_code: '+234', value: 'NG' },
	{ label: 'Норвегия', dial_code: '+47', value: 'NO' },
	{ label: 'ОАЭ', dial_code: '+971', value: 'AE' },
	{ label: 'Пакистан', dial_code: '+92', value: 'PK' },
	{ label: 'Панама', dial_code: '+507', value: 'PA' },
	{ label: 'Парагвай', dial_code: '+595', value: 'PY' },
	{ label: 'Перу', dial_code: '+51', value: 'PE' },
	{ label: 'Филиппины', dial_code: '+63', value: 'PH' },
	{ label: 'Польша', dial_code: '+48', value: 'PL' },
	{ label: 'Португалия', dial_code: '+351', value: 'PT' },
	{ label: 'Россия', dial_code: '+7', value: 'RU' },
	{ label: 'Саудовская Аравия', dial_code: '+966', value: 'SA' },
	{ label: 'Сербия', dial_code: '+381', value: 'RS' },
	{ label: 'Сингапур', dial_code: '+65', value: 'SG' },
	{ label: 'Словакия', dial_code: '+421', value: 'SK' },
	{ label: 'Словения', dial_code: '+386', value: 'SI' },
	{ label: 'Южная Африка', dial_code: '+27', value: 'ZA' },
	{ label: 'Испания', dial_code: '+34', value: 'ES' },
	{ label: 'Швеция', dial_code: '+46', value: 'SE' },
	{ label: 'Швейцария', dial_code: '+41', value: 'CH' },
	{ label: 'Турция', dial_code: '+90', value: 'TR' },
	{ label: 'Уганда', dial_code: '+256', value: 'UG' },
	{ label: 'Украина', dial_code: '+380', value: 'UA' },
	{ label: 'Великобритания', dial_code: '+44', value: 'GB' },
	{ label: 'США', dial_code: '+1', value: 'US' },
	{ label: 'Узбекистан', dial_code: '+998', value: 'UZ' }
]
